language: android
sudo: false
before_script:
  - echo sdk.dir $ANDROID_HOME > local.properties
script:
  - jdk_switcher use oraclejdk8
  - export TERM=dumb
  - export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
  - ./gradlew build
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
  licenses:
    - '.+'
before_install:
 - yes | sdkmanager "platforms;android-27"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
