language: android
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - export JAVA_OPTS="-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
  - export TERM=dumb
  - echo sdk.dir $ANDROID_HOME > local.properties
  - ./gradlew assembleDebug -x lint
android:
  components:
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository


